FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    openssh-server \
    x11-apps \
    x11-utils \
    xterm \
    xauth \
    python3 \
    python3-tk \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /var/run/sshd
RUN useradd -m -s /bin/bash testuser
RUN echo 'testuser:sshterm' | chpasswd

# Overwrite sshd_config
RUN echo "Port 22" > /etc/ssh/sshd_config && \
    echo "PermitRootLogin no" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "KbdInteractiveAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "UsePAM yes" >> /etc/ssh/sshd_config && \
    echo "X11Forwarding yes" >> /etc/ssh/sshd_config && \
    echo "X11UseLocalhost no" >> /etc/ssh/sshd_config && \
    echo "PrintMotd no" >> /etc/ssh/sshd_config && \
    echo "LogLevel DEBUG3" >> /etc/ssh/sshd_config

# SSH login fix
RUN sed 's@session\\s*required\\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

# Pre-generate host keys
RUN ssh-keygen -A

COPY test_ui.py /home/testuser/test_ui.py
RUN chown testuser:testuser /home/testuser/test_ui.py

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D", "-e"]
